export const products = [
  { id: 1, name: "Laptop", category: "electronics", price: 1200, inStock: true },
  { id: 2, name: "Phone", category: "electronics", price: 800, inStock: false },
  { id: 3, name: "T-Shirt", category: "clothing", price: 25, inStock: true },
  { id: 4, name: "Jeans", category: "clothing", price: 60, inStock: false },
  { id: 5, name: "Smartwatch", category: "electronics", price: 250, inStock: true },
  { id: 6, name: "Sneakers", category: "clothing", price: 90, inStock: true },
  { id: 7, name: "Headphones", category: "electronics", price: 150, inStock: true },
  { id: 8, name: "Backpack", category: "clothing", price: 45, inStock: false },
  { id: 9, name: "Book - JS Guide", category: "books", price: 30, inStock: true },
  { id: 10, name: "Book - HTML & CSS", category: "books", price: 28, inStock: true },
  { id: 11, name: "Charger", category: "electronics", price: 40, inStock: true },
  { id: 12, name: "Monitor", category: "electronics", price: 300, inStock: false },
  { id: 13, name: "Keyboard", category: "electronics", price: 100, inStock: true },
  { id: 14, name: "Jacket", category: "clothing", price: 120, inStock: true },
  { id: 15, name: "Tablet", category: "electronics", price: 650, inStock: true },
  { id: 16, name: "Book - Python", category: "books", price: 35, inStock: false },
  { id: 17, name: "Mouse", category: "electronics", price: 45, inStock: true },
  { id: 18, name: "Socks", category: "clothing", price: 10, inStock: true },
  { id: 19, name: "HDMI Cable", category: "electronics", price: 15, inStock: false },
  { id: 20, name: "Hat", category: "clothing", price: 20, inStock: true },
  { id: 21, name: "Webcam", category: "electronics", price: 90, inStock: true },
  { id: 22, name: "Book - Algorithms", category: "books", price: 50, inStock: true },
  { id: 23, name: "Dress", category: "clothing", price: 75, inStock: false },
  { id: 24, name: "Blender", category: "electronics", price: 130, inStock: true },
  { id: 25, name: "Belt", category: "clothing", price: 25, inStock: true },
  { id: 26, name: "Book - React", category: "books", price: 42, inStock: false },
  { id: 27, name: "Earbuds", category: "electronics", price: 85, inStock: true },
  { id: 28, name: "Scarf", category: "clothing", price: 30, inStock: true },
  { id: 29, name: "Fan", category: "electronics", price: 60, inStock: true },
  { id: 30, name: "Book - Data Structures", category: "books", price: 45, inStock: true }
]